name: Pokemon Monitor
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *' # checks every 5 mins, but only pings you hourly
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: node monitor.js
